### ISSUE TITLE
potential error in computation of MAP in solveID.m

### ISSUE THREAD

**Issue by nunoguedelha** [iron76/bnt_time_varying#17]
While going through the implementation of accelerations estimation in `solveID.m`, I found an apparent discrepancy between the expression of `d` (actually `\mu_{d|y}`) found in [solveID.m Line 52](https://github.com/iron76/bnt_time_varying/blob/master/src/%40ANEA/solveID.m#L52), and the equations described in [this wiki](http://wiki.codyco.eu.dev/doku.php?id=analytic_solution_of_the_maximum-a-posteriori_dynamics&#computing_p_boldsymbol_d_boldsymbol_y) as we can see in the below screenshot :
![screen shot 2016-01-07 at 18 05 27](https://cloud.githubusercontent.com/assets/6848872/12176807/7e430a56-b569-11e5-898a-bb2d25484bb6.png)

The term `\Sigma_d^{-1} \mu_d` is missing. @iron76 would this be the result of a simplification I missed?

**Comment by iron76** [comment]
The reason is mu_d is always zero.
